# Generated by Django 5.2 on 2025-09-27 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('engagement_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_on_project', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Source',
            fields=[
                ('feedback_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_source_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_STD',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('role_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilization_Type',
            fields=[
                ('utilization_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('utilization_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentGoal',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done')], default='planned', max_length=20)),
                ('plan_id', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='home.developmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_growth', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('engagement_id', models.ForeignKey(blank=True, db_column='engagement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.engagement')),
                ('feedback_source_id', models.ForeignKey(blank=True, db_column='feedback_source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.feedback_source')),
                ('author_person_id', models.ForeignKey(blank=True, db_column='author_person_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_given', to='home.person')),
                ('subject_person_id', models.ForeignKey(db_column='subject_person_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='home.person')),
            ],
        ),
        migrations.AddField(
            model_name='engagement',
            name='person_id',
            field=models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='home.person'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='home.project'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField()),
                ('engagement_id', models.ForeignKey(blank=True, db_column='engagement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.engagement')),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='home.person')),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Rating',
            fields=[
                ('review_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='home.rating_std')),
                ('review_id', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='home.review')),
            ],
        ),
        migrations.AddField(
            model_name='developmentplan',
            name='review_id',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='home.review'),
        ),
        migrations.AddField(
            model_name='person',
            name='role_id',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.role'),
        ),
        migrations.CreateModel(
            name='Utilization',
            fields=[
                ('utilization_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('hours', models.FloatField()),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='home.person')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='home.project')),
                ('utilization_type_id', models.ForeignKey(db_column='utilization_type_id', on_delete=django.db.models.deletion.CASCADE, to='home.utilization_type')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together={('person_id', 'project_id', 'start_date')},
        ),
    ]
